# Welcome to 

In [1]:
import numpy as np
myarr = np.array([6,98,65,7],np.int8)
myarr


array([ 6, 98, 65,  7], dtype=int8)

In [2]:
print(myarr)
myarr[2]

[ 6 98 65  7]


65

In [3]:
myarr[0] and myarr[1]

98

In [4]:
myarr = np.array([[6,98,65,7]],np.int32)
myarr[0,3]


7

In [5]:
myarr[0,1]

98

In [6]:
myarr.shape

(1, 4)

In [7]:
myarr.dtype

dtype('int32')

In [8]:
myarr[0,2]=28  # change the value
myarr

array([[ 6, 98, 28,  7]])

In [9]:
myarr

array([[ 6, 98, 28,  7]])

# Array creation: Conversion from other Python structure

In [95]:
listarray= np.array([[1,2,3,],[4,5,6],[7,8,9]])
listarrayr = np.array([[2,3,4],[5,6,7],[8,9,1]])

In [97]:
listarray + listarrayr

array([[ 3,  5,  7],
       [ 9, 11, 13],
       [15, 17, 10]])

In [98]:
listarray - listarrayr

array([[-1, -1, -1],
       [-1, -1, -1],
       [-1, -1,  8]])

In [101]:
v= listarray * listarrayr
print(v)

[[ 2  6 12]
 [20 30 42]
 [56 72  9]]


In [103]:
v.transpose()

array([[ 2, 20, 56],
       [ 6, 30, 72],
       [12, 42,  9]])

In [105]:
v *.5

array([[ 1. ,  3. ,  6. ],
       [10. , 15. , 21. ],
       [28. , 36. ,  4.5]])

In [107]:
v.ravel()

array([ 2,  6, 12, 20, 30, 42, 56, 72,  9])

In [92]:
listarray.dtype

dtype('int32')

In [13]:
listarray.shape

(3, 3)

In [14]:
listarray.size

9

In [15]:
np.array({85,85,69}) # to make dtype object is not efficient :
                     #generally use integer and float..

array({85, 69}, dtype=object)

In [16]:
zeros = np.zeros((2,3))

In [17]:
zeros 

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
arman= np.arange(10)

In [19]:
arman

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
#import numpy as np
space = np.linspace(1,50,10)

In [21]:
print(space)


[ 1.          6.44444444 11.88888889 17.33333333 22.77777778 28.22222222
 33.66666667 39.11111111 44.55555556 50.        ]


In [22]:
lspace = np.linspace(1,5,5)

In [23]:
lspace

array([1., 2., 3., 4., 5.])

In [111]:
emp = np.empty((2,4))

In [112]:
emp

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 3.71537366e-321, 4.78389263e+255,
        3.70494538e+289]])

In [26]:
emp_like = np.empty_like(lspace)

In [27]:
emp_like

array([1., 2., 3., 4., 5.])

In [28]:
ide = np.identity(45)

In [29]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [30]:
ide.shape

(45, 45)

In [31]:
import numpy as np
arr = np.arange(99)
print(arr)
print(arr.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98]
(99,)


In [32]:
arr.reshape(3,33)         

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [33]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [34]:
arr = arr.reshape(3,33)

In [35]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [106]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [37]:
 arr = arr.ravel()

In [38]:
arr.shape

(99,)

# axis

In [39]:
x = ([[2,5,6],[4,3,9],[1,2,3]])

In [40]:
ar = np.array(x)

In [41]:
ar

array([[2, 5, 6],
       [4, 3, 9],
       [1, 2, 3]])

In [136]:
ar.max(axis = 1)

array([6, 4, 3])

In [43]:
ar.sum( axis = 1)

array([13, 16,  6])

In [116]:
ar.transpose()

array([[2, 4, 1],
       [5, 3, 2],
       [6, 0, 3]])

In [118]:
ar.flat

In [47]:
ar.ndim

2

In [125]:
ar.ndim

2

In [129]:
ar.shape

(3, 3)

In [48]:
ar.size

9

In [49]:
ar.nbytes  # how much bytes consume

36

In [50]:
one = np.array([12,500,4,78,6])

In [51]:
one.argmax()

1

In [52]:
one.argmin()

2

In [53]:
one.argsort() # increasing form

array([2, 4, 0, 3, 1], dtype=int64)

In [54]:
ar

array([[2, 5, 6],
       [4, 3, 9],
       [1, 2, 3]])

In [138]:
ar.argmin()

5

In [139]:
ar.argmax()

2

In [57]:
ar.argmax(axis=0)

array([1, 0, 1], dtype=int64)

In [58]:
ar.argmin(axis=0)

array([2, 2, 2], dtype=int64)

In [59]:
ar.argmax(axis = 1)

array([2, 2, 2], dtype=int64)

In [60]:
ar.argsort(axis= 1)

array([[0, 1, 2],
       [1, 0, 2],
       [0, 1, 2]], dtype=int64)

In [61]:
print("ar",ar)
print(ar.argsort(axis= 0))


ar [[2 5 6]
 [4 3 9]
 [1 2 3]]
[[2 2 2]
 [0 1 0]
 [1 0 1]]


In [62]:
ar.ravel()

array([2, 5, 6, 4, 3, 9, 1, 2, 3])

In [63]:
ar

array([[2, 5, 6],
       [4, 3, 9],
       [1, 2, 3]])

In [64]:
ar2 = np.array([[1,2,1],[4,0,6],[8,1,0]])

In [65]:
ar + ar2

array([[ 3,  7,  7],
       [ 8,  3, 15],
       [ 9,  3,  3]])

In [66]:
ar * ar2

array([[ 2, 10,  6],
       [16,  0, 54],
       [ 8,  2,  0]])

In [67]:
np.sqrt(ar)

array([[1.41421356, 2.23606798, 2.44948974],
       [2.        , 1.73205081, 3.        ],
       [1.        , 1.41421356, 1.73205081]])

In [68]:
ar

array([[2, 5, 6],
       [4, 3, 9],
       [1, 2, 3]])

In [69]:
ar.sum()

35

In [70]:
ar.max()

9

In [71]:
ar.min()

1

In [72]:
np.where(ar>5)


(array([0, 1], dtype=int64), array([2, 2], dtype=int64))

In [73]:
ar

array([[2, 5, 6],
       [4, 3, 9],
       [1, 2, 3]])

In [74]:
m=np.array([[1,2,3],[4,5,6],[7,1,0]])

In [75]:
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [76]:
np.where(m>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [77]:
np.where(m<5)

(array([0, 0, 0, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2], dtype=int64))

In [78]:
np.count_nonzero(m)

8

In [79]:
np.nonzero(m)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [80]:
ar[1,2]=0

In [81]:
np.nonzero(m)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [82]:
import sys

In [83]:
py_ar = [0,4,55,2]

In [84]:
np_ar = np.array(py_ar)

In [85]:
sys.getsizeof(1) * len(py_ar)

112

In [86]:
import sys
py_ar = [0,4,55,2]
np_ar = np.array(py_ar)
sys.getsizeof(1) * len(py_ar)

112

In [87]:
np_ar.itemsize * np_ar.size

16

In [88]:
np_ar.tolist()

[0, 4, 55, 2]

In [89]:
import numpy as np
import pandas as pd
a = np.array([0,1,22,33])
s = pd.Series(a)
print(s)

0     0
1     1
2    22
3    33
dtype: int32


In [90]:
z = pd.DataFrame(a)
print(z)

    0
0   0
1   1
2  22
3  33


In [113]:
from tkinter import *
master = Tk()
var1 = IntVar()
Checkbutton(master, text='male', variable=var1).grid(row=0, sticky=W)
var2 = IntVar()
Checkbutton(master, text='female', variable=var2).grid(row=1, sticky=W)
mainloop()