In [1]:
import numpy as np

twoDarray = np.array([[11,125,10,6],
                    [10,14,11,5],
                    [12,17,12,8],
                    [15,18,14,9]])
print(twoDarray)
# space complexity --> O(n^2)
# time complexity --> O(n *m)--> O(n)

[[ 11 125  10   6]
 [ 10  14  11   5]
 [ 12  17  12   8]
 [ 15  18  14   9]]


In [5]:
NewtwoDarray = np.insert(twoDarray,0,[[1,2,3,4]], axis = 1)
NewtwoDarray   # axis=1  ---> column wise

array([[  1,  11, 125,  10,   6],
       [  2,  10,  14,  11,   5],
       [  3,  12,  17,  12,   8],
       [  4,  15,  18,  14,   9]])

In [7]:
NewtwoDarray = np.insert(twoDarray,3,[[1,2,3,4]], axis = 0
                        )
NewtwoDarray      # axis = 0 ---> row wise
# time complexity --> O(n *m)--> O(n)

array([[ 11, 125,  10,   6],
       [ 10,  14,  11,   5],
       [ 12,  17,  12,   8],
       [  1,   2,   3,   4],
       [ 15,  18,  14,   9]])

In [8]:
NewtwoDarray = np.append(twoDarray,[[1,2,3,4]], axis = 0)
                        
NewtwoDarray      # axis = 0 ---> row wise

array([[ 11, 125,  10,   6],
       [ 10,  14,  11,   5],
       [ 12,  17,  12,   8],
       [ 15,  18,  14,   9],
       [  1,   2,   3,   4]])

In [30]:
import numpy as np

twoDarray = np.array([[11,125,10,6,7],
                    [10,14,11,5,10],
                    [12,17,12,8,25],
                    [15,18,14,9,95]])
print(len(twoDarray[0])) #  ---> no of columns
print(len(twoDarray))     # ---> no of rows

def accessElement(array,RowIndex, ColumnIndex):
    if RowIndex >= len(array) and ColumnIndex >= len(array[0]):
        print("incorrect index")
    else:
        print(array[RowIndex][ColumnIndex])
(accessElement(twoDarray,2,2))

# access time complexity is O(1)
# space complexity is also O(1)

5
4
12


# traversling two dimentional array

In [31]:
import numpy as np

twoDarray = np.array([[11,125,10,6,7],
                    [10,14,11,5,10],
                    [12,17,12,8,25],
                    [15,18,14,9,95]])
def traverseArray(array):
    for i in range(len(array)):
        for j in range(len(array[0])):
            print(array[i][j])
traverseArray(twoDarray)
# time complexity O(n)
# space complexity O(1)

11
125
10
6
7
10
14
11
5
10
12
17
12
8
25
15
18
14
9
95


# searching element in 2D array

In [42]:
import numpy as np

twoDarray = np.array([[11,125,10,6,7],
                    [10,14,11,5,10],
                    [12,17,12,8,25],
                    [15,18,14,9,95]])
def SearchElement(array,element):
    for i in range(len(array)):
        for j in range(len(array[0])):
            if array[i][j] == element:
                return "The value is located at index:"+str(i)+" "+str(j)
    return "the element is not found"
print(SearchElement(twoDarray,7))

The value is located at index:0 4


# deleting element in 2D array

In [46]:
import numpy as np

twoDarray = np.array([[11,125,10,6,7],
                    [10,14,11,5,10],
                    [12,17,12,8,25],
                    [15,18,14,9,95]])
newArray = np.delete(twoDarray,2,axis = 0)
print(newArray)
# Time complexity and Space complexity both ----> O(n*m)--> O(n) because after deletion print the remaing data

[[ 11 125  10   6   7]
 [ 10  14  11   5  10]
 [ 15  18  14   9  95]]
