# basic gui , minsize and maxsize

In [3]:
import tkinter as tk
from tkinter import ttk

win=tk.Tk()
win.title("Basic GUI")
win.geometry("500x400")

win.minsize(200,200)
win.maxsize(900,600)

label_1=ttk.Label(win, text="Noida, New Delhi").grid()

win.mainloop()


# to take image 

In [13]:
from tkinter import  *
#from tkinter import ttk
from PIL import Image, ImageTk
win = tk.Tk()
win.title("To take image from file")
win.geometry("1000x900")

image = Image.open("WhatsApp Image 2022-05-03 at 7.37.43 PM")  #file name
arman= ImageTk.PhotoImage(image)

label = Label(image=arman).grid()

win.mainloop()

FileNotFoundError: [Errno 2] No such file or directory: 'WhatsApp Image 2022-05-03 at 7.37.43 PM'

In [ ]:
from tkinter import *

win=Tk()


# Notes

In [ ]:
#import label attributes
text = adds the text
bd = background
fg = foreground
font = sets the font
padx = x padding
pady = y padding
relief = border styling= SUNKEN, RAISED, GROOVE, RIDGE

important Pack options
anchor = nw, nw, sw, we
side = top, bottom, left, right
fill= X or  Y

# basic

In [109]:
# import tkinter as tk
# from tkinter import ttk
from tkinter import *

win=tk.Tk()
win.geometry("200x300")
win.title("gui")
label= ttk.Label(text="""According to consensus in modern genet\n
anatomically modern humans first arrived on t\n
he Indian subcontinent from Africa between 73,\n
000 and 55,000 years ago.[1] However, the \n
earliest known human \n
remains in South Asia.""",background = "red",foreground="blue")
label.pack( anchor="sw")
win.mainloop()

In [55]:
#import tkinter as tk
from tkinter import *

win=tk.Tk()
win.geometry("200x300")     #font=("Gill",19,"bold") can write
win.title("Arman ")         #padx=23, pady=44 BOTTOM
                            #relief=SUNKEN # fill = X Y


l1=ttk.Label(win, text="aaaaaaaaaaaaaaaaaaaaaaaaaa",font="Gill 25 bold", foreground="white", background="red",borderwidth=3)
l1.pack(anchor = "ne", fill=X, side=TOP, padx=20, pady=20)
#l1.pack(side="bottom", fill=X)
win.mainloop()

# frame

In [1]:
# import tkinter as tk
# from tkinter import ttk
from tkinter import *

root=tk.Tk()
root.geometry("500x600")

f1= Frame(root, background="grey", borderwidth=5,relief=SUNKEN)
f1.pack(side = LEFT,fill="y",pady=142)

f2=Frame(root, background="grey", relief=SUNKEN)
f2.pack(side=TOP, fill= "x")

l=Label(f1,text="Project python")
l.pack(pady=142)

l=Label(f2,text="welcome to sublime text",foreground="red")
l.pack(padx=150)

root.mainloop()

NameError: name 'tk' is not defined

In [2]:
from tkinter import *
win = Tk()


f1 = Frame(win, width = 200, height = 250, bg = "grey", relief = SUNKEN).pack()
l1 = Label(f1, text= "arman").pack(anchor = 'n')

win.mainloop()

In [63]:
from tkinter import *
win = Tk()
win.geometry("200x250")
c = Canvas(win).pack()

c.create_line(0,0,100,100)
c.create_line(0,0,800,0,fill="red")
win.mainloop()

AttributeError: 'NoneType' object has no attribute 'create_line'

In [1]:
from tkinter import *

win=tk.Tk()
win.geometry("200x250")
win.title("Python project by Arman")

frame_1= Frame(win, background="blue", relief=GROOVE)
frame_1.pack(side=LEFT, fill="x")

frame_2= Frame(win,background="blue",relief=SUNKEN)
frame_2.pack(side=RIGHT)

frame_3= Frame(win, background="blue",relief=SUNKEN)
frame_3.pack(side=TOP)

frame_4= Frame(win,background="blue",relief=SUNKEN)
frame_4.pack(side=BOTTOM)

label_1=Label(frame_1, text="first frame in left side", background="grey",font="Gill 20 bold" ,foreground = "red")
label_1.pack(pady=200)

label_2=Label(frame_2, text="second frame in right side", background="grey",font="Gill 20 bold",foreground = "red")
label_2.pack(pady=200)

label_3=Label(frame_3, text="third frame in top side", background="grey",font="Gill 20 bold",foreground = "red")
label_3.pack(padx=200)

label_4=Label(frame_4, text="fourth frame in bottom side", background="grey",font="Gill 20 bold",foreground = "red")
label_4.pack(padx=200)

win.mainloop()




NameError: name 'tk' is not defined

# Button

In [4]:
from tkinter import *

win=tk.Tk()
win.geometry("200x250")
win.title("Python project by Arman")
def hello():
    print("hello button")
def name():
    print("your name is arman")
frame1=Frame(win, borderwidth=6,bg="grey", relief=RAISED,)
frame1.pack(side=LEFT, anchor="nw")

b1=Button(frame1, fg="red", text="Print now",command=hello)
b1.pack()

frame2=Frame(win, borderwidth=6,bg="grey", relief=SUNKEN)
frame2.pack(side=LEFT, anchor="nw")

b2=Button(frame2, fg="red", text="Print now",command=name)
b2.pack()
win.mainloop()




hello button
your name is arman
hello button


In [5]:
from tkinter import *
window=tk.Tk()
window.geometry("200x300")
window.title("Button ")

def your_name():
    print("your name is MohammadArman")
    
def college_name():
    print("your college name is NIET")

def branch_name():
    print("your branch name is B.Tech")

def freinds_name():
    print("freinds name: Arman, faishal, ali, wasimul,firdosh")

frame_1=Frame(window, background="blue",borderwidth=6)
frame_1.pack(side=LEFT,anchor="nw")

b1=Button(frame_1, text="your name",background= "white", foreground="red",command=your_name, font="Gill 10 bold")
b1.pack(side=LEFT)


b2=Button(frame_1, text="college name ",background= "white", foreground="red",command=college_name, font="Gill 10 bold")
b2.pack(side=LEFT)

b3=Button(frame_1, text="branch name",background= "white", foreground="red",command=branch_name, font="Gill 10 bold")
b3.pack(side=LEFT)

b4=Button(frame_1, text="freinds name",background= "white", foreground="red",command=freinds_name, font="Gill 10 bold")
b4.pack(side=LEFT)



window.mainloop()

NameError: name 'tk' is not defined

# notes 

In [ ]:
#variable classes in tkinter
# BooleanVar , DoubleVar, IntVar, StringVar

# grid and Entry 

In [6]:
from tkinter import *

win=tk.Tk()
win.geometry("200x300") 
win.title("for dance classses")
win.configure(bg="yellow")

win.minsize(400,450)
win.maxsize(600,700)

def output():
    print(f"user name is {e1.get()}")
    print(f"user team's name is {e2.get()}")


l1=Label(win, text="Enter your name: ",font="Gill 15 bold", foreground="blue")
l1.grid(row=0, column=0)

l2=Label(win, text="Your team's name: ",font="Gill 15 bold", foreground="blue")
l2.grid(row=1, column=0)

namevar=StringVar()
teamvar=StringVar()

e1=Entry(win, textvariable=namevar)
e1.grid(row=0,column=1)

e2=Entry(win, show="*", textvariable= teamvar)
e2.grid(row=1 ,column=1)

b1=Button(win, text="Submit",font="Calibri 15 bold", foreground="blue", command=output,padx=30).grid()
win.mainloop()

user name is Arman
user team's name is affansufian


# name, phone, gender, emergency,paymentmode

In [7]:
from tkinter import *

win=Tk()
win.title("Your information")
win.geometry("400x450")
#win.configure(bg="yellow")

win.minsize(600,650)
win.maxsize(900,1000)


def output():
    print("its work")# print(f"user name is {e1.get()}")
    print(f"your name is {ename.get()},gender is {egender.get()},phone no: {ephone.get()},emergency no; {eemergency.get()},paymode: {epay.get()}")
    with open("GUI.txt","a") as f:
        f.write(f"your name is {ename.get()},gender is {egender.get()},phone no: {ephone.get()},emergency no; {eemergency.get()},paymode: {epay.get()}\n")
    
    #     print(f"gender is {egender.get()}")
#     print(f"phone no: {ephone.get()}")
#     print(f"emergency no; {eemergency.get()}")
#     print(f"paymode: {epay.get()}")
    
#labels
Label(win, text = "WELCOME  WELCOME WELCOME ", font="Gill 20 bold", pady=15).grid(row=0, column=3)

lname=Label(win, text="Enter your name ",font="Gill 15 bold")
lname.grid(row=2, column=0)

lgender=Label(win, text="Enter your gender ",font="Gill 15 bold")
lgender.grid(row=3, column=0)

lphone=Label(win, text="your contact no.",font="Gill 15 bold")
lphone.grid(row=4, column=0)

lemergency=Label(win, text="Emergency contact no. ",font="Gill 15 bold")
lemergency.grid(row=5, column=0)

lpaymode=Label(win, text="payment mode ",font="Gill 15 bold")
lpaymode.grid(row=6, column=0)

#packing values
namevalue=StringVar()
gendervalue=StringVar()
phonevalue=StringVar()
emergencyvalue=StringVar()
payvalue=StringVar()
#check=IntVar()

#entry
ename=Entry(win, textvariable=namevalue)
ename.grid(row=2, column=3)

egender=Entry(win,textvariable=gendervalue)
egender.grid(row=3, column=3)

ephone=Entry(win,textvariable=phonevalue,show="*")
ephone.grid(row=4, column=3)

eemergency=Entry(win, textvariable=emergencyvalue,show="*")
eemergency.grid(row=5, column=3)

epay=Entry(win, textvariable=payvalue)
epay.grid(row=6, column=3)

#submit
button=Button(win, text="Submit", command=output).grid(row=8 , column=2)
#check=Checkbutton(win,text="Want to pre-book your meals!",variable=check).grid(row=7, column=3)
#radio=Radiobutton(win, text="some").grid(row=9,column=2)
win.mainloop()

its work
your name is arman,gender is male,phone no: 9572300101,emergency no; 7371934996,paymode: paytm


# from google

In [8]:
import tkinter as tk
from tkinter import ttk
# root window
root = tk.Tk()
root.geometry("240x100")
root.title('Login')
root.resizable(0, 0)

# configure the grid
root.columnconfigure(0, weight=1)
root.columnconfigure(1, weight=3)


# username
username_label = ttk.Label(root, text="Username:")
username_label.grid(column=0, row=0, sticky=tk.W, padx=5, pady=5)

username_entry = ttk.Entry(root)
username_entry.grid(column=1, row=0, sticky=tk.E, padx=5, pady=5)

# password
password_label = ttk.Label(root, text="Password:")
password_label.grid(column=0, row=1, sticky=tk.W, padx=5, pady=5)

password_entry = ttk.Entry(root,  show="*")
password_entry.grid(column=1, row=1, sticky=tk.E, padx=5, pady=5)

# login button
login_button = ttk.Button(root, text="Login")
login_button.grid(column=1, row=3, sticky=tk.E, padx=5, pady=5)


root.mainloop()


# Canvas

In [48]:
from tkinter import *
canvas=Tk()
canvas.geometry("500x600")
canvas.title("Canvas project")

c=Canvas(canvas, width=300, height=400)
c.pack()

c.create_line(0,0,800,0,fill="red")
c.create_line(0,400,800,0, fill="red")

c.create_rectangle(0,0,190,320,fill="blue")
c.create_text(45,60, text="Arman", font="Gill 22 bold")
c.create_oval(90,90,90,90,fill=("yellow"))
canvas.mainloop()

# generator iterator

In [19]:
def greeting():
    print("hi")
    yield 1
    print("arman")
    yield 10
    print("nietian")
    yield 30
obj=greeting()
result=next(obj)
result=next(obj)
print(result)
print(result)

hi
arman
10
10


In [20]:
class Squares:
    def __init__(self, length):
        self.length = length
        self.current = 0

    def __iter__(self):
        return self

    def __next__(self):
        result = self.current ** 2

        self.current += 1

        if self.current > self.length:
            raise StopIteration

        return result
    
length = 5
square = Squares(length)
for s in square:
    print(s)

0
1
4
9
16


In [27]:
def square(length):
    for i in range(length):
        yield i**2
length=5
result=square(length)
for s in result:
    print(s)        

0
1
4
9
16


# Events

In [82]:
from tkinter import *
win=Tk()
win.geometry("644x334")

def arman(event):
    print(f"you clicked successful{event.x},{event.y}")

widget = Button(win, text="click me ")
widget.pack()

widget.bind("<Button-1>",arman)
widget.bind("<Double-1>",quit)

win.mainloop()



you clicked successful26,18
you clicked successful36,14


In [73]:
from tkinter import *
win=Tk()
win.geometry("200x300")
win.title(" A \ T you ")

def change():
    win=Tk()
    win.title("new window using Canvas")
    w=input("Enter width of gui: ")
    h=input("Enter height of gue: ")
    c=Canvas(win, width=w, height=h).pack()
    win.mainloop()


button=Button(win, text="clict to change",command= change)
button.grid()

win.mainloop()

Enter width of gui: 500
Enter height of gue: 300
Enter width of gui: 100
Enter height of gue: 200


# to make menu edit file...

In [9]:
from tkinter import *
win=Tk()
win.geometry("220x330")
win.title("NotePad by Arman")

def Myfunc():
    print(f"everything is going well")


filemenu=Menu(win)
m1=Menu(filemenu, tearoff=0)
m1.add_command(label="new project",command=Myfunc)
m1.add_command(label="save",command=Myfunc)
m1.add_separator()
win.config(men=filemenu)

filemenu.add_cascade(label="File", men=m1)

#editmenu=Edit(win)
m2=Menu(filemenu, tearoff=0)
m2.add_command(label="new project",command=Myfunc)
m2.add_command(label="save",command=Myfunc)
m2.add_separator()
win.config(men=filemenu)

filemenu.add_cascade(label="Edit", men=m2)

win.mainloop()

In [75]:

from tkinter import *

def save():
    print("successful")

win=Tk()
win.title("Note")
win.geometry("200x250")

mainmenu = Menu(win)

m1 = Menu(mainmenu, tearoff=0)
m1.add_command(label = "save",command = save)
m1.add_separator()
m1.add_command(label = "save as", command= save)
win.configure(menu=mainmenu)

mainmenu.add_cascade(label="file", menu= m1)

win.mainloop()

successful


In [54]:
from tkinter import *
win=Tk()
win.geometry("220x330")
win.title("NotePad by Arman")

def save():
    print("your click on save")
def save_as():
    print("you click on save as")
def edit():
    print("you click on edit")

mainmenu=Menu(win)
m1=Menu(mainmenu,tearoff=0)
m1.add_command(label="save", command=save)
m1.add_command(label="save_as", command=save_as)
m1.add_command(label="edit", command=edit)
mainmenu.add_cascade(label="File",menu=m1)
win.config(menu=mainmenu)

win.mainloop()



In [10]:
from tkinter import *
import tkinter.messagebox as tmsg
win=Tk()
win.title("Note Pad")
win.geometry("300x400")

def save():
    print("saved")
def save_as():
    print("save_as")
def find():
    print("find")
def cut():
    print("cut")
def copy():
    print("copy")
    
def paste():
    print("paste")
def Help():
    print("help")
    tmsg.showinfo("Help","Arman will help you")
    
def rate():
    print("rate us")
    v=tmsg.askquestion("was your experience good?","you used this gui")
    #print(v)
    if v == "yes":
        msg="Great...Rate us on app store please"
    else:
        msg="tell us what went wrong. we will call you soon"
    tmsg.showinfo('experience', msg)

def arman():
    ans = tmsg.askretrycancel("arman se dosti kar lo","sorry arman dost nahi banega aapki")
    if ans:
        print("Retry karne pe bhi kuchh nhi hoga")
    else:
        print("bahut badhiya.....nhi to pitte")
mainmenu=Menu(win)
#file
m1=Menu(mainmenu, tearoff=0)
m1.add_command(label="save", command=save)
m1.add_command(label="save as", command=save_as)
m1.add_command(label="find", command=find)
mainmenu.add_cascade(label="file",menu=m1)
win.config(menu=mainmenu)


m2=Menu(mainmenu, tearoff=0)
m2.add_command(label="cut", command=cut)
m2.add_command(label="copy", command=copy)
m2.add_command(label="paste", command=paste)
mainmenu.add_cascade(label="edit",menu=m2)
win.config(menu=mainmenu)

m3=Menu(mainmenu, tearoff=0)
m3.add_command(label="help", command=Help)
m3.add_command(label="Rate us", command=rate)
m3.add_command(label="befreind",command=arman)
mainmenu.add_cascade(label="help",menu=m3)
win.config(menu=mainmenu)


win.mainloop()



saved
save_as
find
cut
copy
paste
help
rate us
Retry karne pe bhi kuchh nhi hoga
Retry karne pe bhi kuchh nhi hoga


# slider 

In [11]:
from tkinter import  *
import tkinter.messagebox as tmsg
win=Tk()
win.geometry("450x500")
win.title("Slider")

# myslider= Scale(win, from_= 0, to =455, orient=HORIZONTAL)
# myslider.pack()
def getdollar():
    print(f"we have credited {myslider2.get()} dollars to you")
    tmsg.showinfo("Amount Crideted!",f"we have credited {myslider2.get()} dollars to you")
    
Label(win, text="How many dollers do u want?")
myslider2= Scale(win, from_=0, to=100, orient=HORIZONTAL, tickinterval=50)
myslider2.set(35)
myslider2.pack()
button=Button(win, text="get dollars!",command=getdollar, pady=10).pack()

win.mainloop()

we have credited 49 dollars to you


In [73]:
from tkinter import *
import tkinter.messagebox as tmsg

win=Tk()
win.title("Slider project")
win.geometry("200x300")
win.minsize(400,450)
win.maxsize(600,650)

def ok():
    print(f"you give us rating {slider1.get()} star")
    tmsg.showinfo("Taj Hotel",f" you gave rating {slider1.get()} star!!!")
slider1=Scale(win, from_=0, to = 10, orient=HORIZONTAL, tickinterval=2)
slider1.pack()

button=Button(win, text="click here", pady=10, bg="white", fg="blue",command=ok).pack()


win.mainloop()

you give us rating 10 star


# Radiobutton

In [12]:
from tkinter import *
import tkinter.messagebox as tmsg

win=Tk()
win.title("Radiobutton project")
win.geometry("350x450")

def order():
    print(f"you are {var.get()} and your name is {name} ")
    tmsg.showinfo("choosen gender",f"you are {var.get()}")

name=input("name: ")
#var = IntVar()
var = StringVar()
var.set("ARman")
#var.set(1)
Label(win, text= "what would u like to have sir?", font="Gill 15 bold", justify=LEFT, padx=10).pack()

radiok = Radiobutton(win, text="male", pady=15, variable=var, value="male").pack( anchor="w")
radio = Radiobutton(win, text="female", padx=15, variable=var, value="female").pack( anchor="w")
radio = Radiobutton(win, text="transgender", padx=15, variable=var, value="transgender").pack( anchor="w")
radio = Radiobutton(win, text="others", padx=15, variable=var, value="other").pack( anchor="w")

button= Button(win, text="submit now", command=order).pack()
win.mainloop()

name: arman
you are male and your name is arman 


# Listbox

In [13]:
from tkinter import *
import tkinter.messagebox as tmsg
win=Tk()
win.title("Listbox project")
win.geometry("350x450")

def add():
    global i
    lbx.insert(ACTIVE, f"{i}")
    i+=1
i = 0
lbx=Listbox(win)
lbx.pack()
lbx.insert(END, "First item of our listbox")

button=Button(win, text="Add item", command=add)
button.pack()
win.mainloop()

# to update gui window

In [80]:
from tkinter import *
def update():
    print("Updating the gui")
    win.geometry(f"{width.get()}x{height.get()}")
    
win = Tk()
win.geometry("400x500")
width = StringVar()
height = StringVar()
Entry(win, textvariable=width).pack()
Entry(win, textvariable=height).pack()

button=Button(win,text="submit", command=update)
button.pack()

win.mainloop()


# status bar

In [16]:
from tkinter import *

def upload():
    statusvar.set("uploading...")
    sbar.update()
    import time
    time.sleep(2)
    statusvar.set("Ready now")
    

win=Tk()
win.title("Status bar project")
win.geometry("350x450")

statusvar= StringVar()
statusvar.set("Ready")
sbar = Label(win, textvariable= statusvar, anchor="w", relief=SUNKEN)
sbar.pack(side=BOTTOM, fill=X)
Button(win, text="Upload", command=upload).pack()

win.mainloop()

# destroy

In [14]:
from tkinter import *
# def close():
#     import time
#     #time.sleep(2)
#     win.destroy


win=Tk()
win.title("window destroy project")
win.geometry("350x450")
win.configure(bg="white")

width = win.winfo_screenwidth()
height = win.winfo_screenheight()

print(f"{width}x{height}")

button=Button(text="close or destroy", command=win.destroy,bg="red")
button.pack()
win.mainloop()

1536x864


# destroy windows winthin seconds

In [15]:
from tkinter import *
from tkinter import ttk

win = Tk()
win.geometry("200x300")

win.after(5000,win.destroy)

win.mainloop()

In [83]:
from tkinter import *
import tkinter.messagebox as tmsg

def run():
    #name = input("name: ")
    print(f"you are a {var.get()} and yuor name is {name}")
    tmsg.showinfo("chosen gender",f"your are a {var.get()}")
win=Tk()
win.title("Radiobutton")


var = StringVar()
var.set("arman")

r1 = Radiobutton(win, text= "Male", variable=var, value="Male").pack(anchor=N)
r2 = Radiobutton(win, text = "Female", variable = var, value= "Female").pack(anchor = N)

button = Button(win, text = "Submit", command = run).pack()

win.mainloop()

you are a Male and yuor name is a


In [84]:
from tkinter import *
win=Tk()

#width=win.winfo_screenwidth()
height = win.winfo_screenheight()

width = win.winfo_screenwidth()
print(f"{width}")

print(f"{width}x{height}") 

win.mainloop()

1536
1536x864


In [67]:
from tkinter import *

def run():
    print("successful")
    print(f"you click window size is width {width.get()} and height {height.get()}")
    win.geometry(f"{width.get()}x{height.get()}")
win=Tk()
win.geometry("250x300")

width = StringVar()
height = StringVar()

w_entry = Entry(win, textvariable = width).pack()
h_entry = Entry(win, textvariable = height).pack()

button = Button(win,text="click to change size", command= run).pack()

win.mainloop()

successful
you click window size is width 300 and height 200
successful
you click window size is width 300 and height 400


# slide

In [4]:
from tkinter import *
import tkinter.messagebox as tmsg

def run():
    print(f"you choose {slider.get()}")
    tmsg.showinfo("normal game",f"you choose {slider.get()}")
    
    

win = Tk()

slider = Scale(win, from_=0, to = 10, tickinterval=2, orient= HORIZONTAL)
slider.pack()

button = Button(win, text  = "click",bg="grey", command = run).pack()

win.mainloop()

you choose 5


In [100]:
from tkinter import *
win=Tk()
win.title("file menu")
win.geometry("200x250")

def save():
    print("you click on save")
def find():
    print("you click on find")


mainmenu = Menu(win)

m1 = Menu(mainmenu, tearoff = 0)
m1.add_command(label="save", command=save)
m1.add_separator()
m1.add_command(label = "find", command = find)
m1.add_separator()

win.config(menu=mainmenu)
mainmenu.add_cascade(label="File", menu = m1)

win.mainloop()

you click on find
you click on save


In [103]:
import numpy as np 
a = np.array([[1,2,3],[4,5,6]]) 
print (a.shape)
print(a)


(2, 3)
[[1 2 3]
 [4 5 6]]


In [104]:
import numpy as np 
a = np.array([[1,2,3],[4,5,6]]) 
a.shape = (3,2) 
print (a) 


[[1 2]
 [3 4]
 [5 6]]


In [109]:
import numpy as np 
a = np.array([[1,2,3],[4,5,6]]) 
a.reshape 
print (a) 

[[1 2 3]
 [4 5 6]]


In [112]:
import numpy as np
a = np.arange(21)
print(a)



[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [114]:
a.resize(3,7)
print(a)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]]


In [117]:
b = a.reshape(3,7)
print(b)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]]


In [128]:
import pandas as pd
a = (1,2,3)
b = pd.Series(a)
b

0    1
1    2
2    3
dtype: int64

In [125]:
print(b[1])

2


In [130]:
import pandas as pd
a = [1,2,3,4]
b =pd.Series(a)
b

0    1
1    2
2    3
3    4
dtype: int64

In [133]:
b = pd.Series(a, index = ["first","second","third","fourth"])
b

first     1
second    2
third     3
fourth    4
dtype: int64

In [134]:
n=pd.Series(a,index=["a","b","c","d"])
n

a    1
b    2
c    3
d    4
dtype: int64

In [136]:
calories = {"day1":420 , "day2":562}
c = pd.Series(calories)
c

day1    420
day2    562
dtype: int64

In [143]:
import pandas as pd
cal = {
    "day":["day1","day2"],
    "calories":[420,386]
}
data = pd.DataFrame(cal, index = ["first","second"])
data

day  calories
first   day1       420
second  day2       386

In [148]:
import numpy as np
a = np.arange(2,11)
a.resize(3,3)
print(a)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [17]:
from tkinter import *
win = Tk() # This is to create a basic window
win.geometry("312x324") # this is for the size of the window 
win.resizable(0, 0) # this is to prevent from resizing the window
win.title("Calculator")
###################Starting with functions ####################
# 'btn_click' function : 
# This Function continuously updates the 
# input field whenever you enter a number
def btn_click(item):
    global expression
    expression = expression + str(item)
    input_text.set(expression)
# 'bt_clear' function :This is used to clear 
# the input field
def bt_clear():
    global expression
    expression = ""
    input_text.set("")
# 'bt_equal':This method calculates the expression 
# present in input field
def bt_equal():
    global expression
    result = str(eval(expression)) # 'eval':This function is used to evaluates the string expression directly
    input_text.set(result)
    expression = ""
expression = ""
# 'StringVar()' :It is used to get the instance of input field
input_text = StringVar()
# Let us creating a frame for the input field
input_frame = Frame(win, width=312, height=50, bd=0, highlightbackground="black", highlightcolor="black", highlightthickness=2)
input_frame.pack(side=TOP)
#Let us create a input field inside the 'Frame'
input_field = Entry(input_frame, font=('arial', 18, 'bold'), textvariable=input_text, width=50, bg="#eee", bd=0, justify=RIGHT)
input_field.grid(row=0, column=0)
input_field.pack(ipady=10) # 'ipady' is internal padding to increase the height of input field
#Let us creating another 'Frame' for the button below the 'input_frame'
btns_frame = Frame(win, width=312, height=272.5, bg="grey")
btns_frame.pack()
# first row
clear = Button(btns_frame, text = "C", fg = "black", width = 32, height = 3, bd = 0, bg = "#eee", cursor = "hand2", command = lambda: bt_clear()).grid(row = 0, column = 0, columnspan = 3, padx = 1, pady = 1)
divide = Button(btns_frame, text = "/", fg = "black", width = 10, height = 3, bd = 0, bg = "#eee", cursor = "hand2", command = lambda: btn_click("/")).grid(row = 0, column = 3, padx = 1, pady = 1)
# second row
seven = Button(btns_frame, text = "7", fg = "black", width = 10, height = 3, bd = 0, bg = "#fff", cursor = "hand2", command = lambda: btn_click(7)).grid(row = 1, column = 0, padx = 1, pady = 1)
eight = Button(btns_frame, text = "8", fg = "black", width = 10, height = 3, bd = 0, bg = "#fff", cursor = "hand2", command = lambda: btn_click(8)).grid(row = 1, column = 1, padx = 1, pady = 1)
nine = Button(btns_frame, text = "9", fg = "black", width = 10, height = 3, bd = 0, bg = "#fff", cursor = "hand2", command = lambda: btn_click(9)).grid(row = 1, column = 2, padx = 1, pady = 1)
multiply = Button(btns_frame, text = "*", fg = "black", width = 10, height = 3, bd = 0, bg = "#eee", cursor = "hand2", command = lambda: btn_click("*")).grid(row = 1, column = 3, padx = 1, pady = 1)
# third row
four = Button(btns_frame, text = "4", fg = "black", width = 10, height = 3, bd = 0, bg = "#fff", cursor = "hand2", command = lambda: btn_click(4)).grid(row = 2, column = 0, padx = 1, pady = 1)
five = Button(btns_frame, text = "5", fg = "black", width = 10, height = 3, bd = 0, bg = "#fff", cursor = "hand2", command = lambda: btn_click(5)).grid(row = 2, column = 1, padx = 1, pady = 1)
six = Button(btns_frame, text = "6", fg = "black", width = 10, height = 3, bd = 0, bg = "#fff", cursor = "hand2", command = lambda: btn_click(6)).grid(row = 2, column = 2, padx = 1, pady = 1)
minus = Button(btns_frame, text = "-", fg = "black", width = 10, height = 3, bd = 0, bg = "#eee", cursor = "hand2", command = lambda: btn_click("-")).grid(row = 2, column = 3, padx = 1, pady = 1)
# fourth row
one = Button(btns_frame, text = "1", fg = "black", width = 10, height = 3, bd = 0, bg = "#fff", cursor = "hand2", command = lambda: btn_click(1)).grid(row = 3, column = 0, padx = 1, pady = 1)
two = Button(btns_frame, text = "2", fg = "black", width = 10, height = 3, bd = 0, bg = "#fff", cursor = "hand2", command = lambda: btn_click(2)).grid(row = 3, column = 1, padx = 1, pady = 1)
three = Button(btns_frame, text = "3", fg = "black", width = 10, height = 3, bd = 0, bg = "#fff", cursor = "hand2", command = lambda: btn_click(3)).grid(row = 3, column = 2, padx = 1, pady = 1)
plus = Button(btns_frame, text = "+", fg = "black", width = 10, height = 3, bd = 0, bg = "#eee", cursor = "hand2", command = lambda: btn_click("+")).grid(row = 3, column = 3, padx = 1, pady = 1)
# fourth row
zero = Button(btns_frame, text = "0", fg = "black", width = 21, height = 3, bd = 0, bg = "#fff", cursor = "hand2", command = lambda: btn_click(0)).grid(row = 4, column = 0, columnspan = 2, padx = 1, pady = 1)
point = Button(btns_frame, text = ".", fg = "black", width = 10, height = 3, bd = 0, bg = "#eee", cursor = "hand2", command = lambda: btn_click(".")).grid(row = 4, column = 2, padx = 1, pady = 1)
equals = Button(btns_frame, text = "=", fg = "black", width = 10, height = 3, bd = 0, bg = "#eee", cursor = "hand2", command = lambda: bt_equal()).grid(row = 4, column = 3, padx = 1, pady = 1)
win.mainloop()